[package]
authors = ["Sotaro Tommykawa"]
description = "Decoder for names of Truetype font."
edition = "2021"
license = "MIT/Apache-2.0"
name = "ttf-name-decoder"
repository = "https://github.com/ssssota/ttf-name-decoder"
version = "0.1.0"

[dependencies]
encoding_rs = "0.8"
