use crate::decoders;
use crate::macros::generate_id_table;
use crate::{Decoder, Error};

pub fn get_decoder(encoding_id: u16, language_id: u16) -> Result<Decoder, Error> {
    get_decoder_from_language_id(language_id)
        .or(get_decoder_from_encoding_id(encoding_id))
}

fn get_decoder_from_language_id(language_id: u16) -> Result<Decoder, Error> {
    match LanguageId::try_from(language_id)? {
        _ => Err("Unsupported"),
    }
}

fn get_decoder_from_encoding_id(encoding_id: u16) -> Result<Decoder, Error> {
    match EncodingId::try_from(encoding_id)? {
        EncodingId::Roman => Ok(decoders::mac_roman_decode),
        EncodingId::Japanese => Ok(decoders::shift_jis_decode),
        EncodingId::ChineseTraditional => Ok(decoders::big5_decode),
        EncodingId::Korean => Ok(decoders::euc_kr_decode),
        EncodingId::Arabic => Ok(decoders::iso_8859_6_decode),
        EncodingId::Hebrew => Ok(decoders::iso_8859_8_decode),
        EncodingId::Greek => Ok(decoders::iso_8859_7_decode),
        EncodingId::Russian => Ok(decoders::cyrillic_decode),
        EncodingId::ChineseSimplified => Ok(decoders::gbk_decode),
        _ => Err("Unsuppoted"),
    }
}

// ref. https://docs.microsoft.com/en-us/typography/opentype/spec/name#macintosh-encoding-ids-script-manager-codes
generate_id_table! {
    EncodingId,
    Roman: 0,
    Japanese: 1,
    ChineseTraditional: 2,
    Korean: 3,
    Arabic: 4,
    Hebrew: 5,
    Greek: 6,
    Russian: 7,
    RSymbol: 8,
    Devanagari: 9,
    Gurmukhi: 10,
    Gujarati: 11,
    Oriya: 12,
    Bengali: 13,
    Tamil: 14,
    Telugu: 15,
    Kannada: 16,
    Malayalam: 17,
    Sinhalese: 18,
    Burmese: 19,
    Khmer: 20,
    Thai: 21,
    Laotian: 22,
    Georgian: 23,
    Armenian: 24,
    ChineseSimplified: 25,
    Tibetan: 26,
    Mongolian: 27,
    Geez: 28,
    Slavic: 29,
    Vietnamese: 30,
    Sindhi: 31,
    Uninterpreted: 32,
}

// ref. https://docs.microsoft.com/en-us/typography/opentype/spec/name#macintosh-language-ids
generate_id_table! {
    LanguageId,
    English: 0,
    French: 1,
    German: 2,
    Italian: 3,
    Dutch: 4,
    Swedish: 5,
    Spanish: 6,
    Danish: 7,
    Portuguese: 8,
    Norwegian: 9,
    Hebrew: 10,
    Japanese: 11,
    Arabic: 12,
    Finnish: 13,
    Greek: 14,
    Icelandic: 15,
    Maltese: 16,
    Turkish: 17,
    Croatian: 18,
    ChineseTraditional: 19,
    Urdu: 20,
    Hindi: 21,
    Thai: 22,
    Korean: 23,
    Lithuanian: 24,
    Polish: 25,
    Hungarian: 26,
    Estonian: 27,
    Latvian: 28,
    Sami: 29,
    Faroese: 30,
    FarsiPersian: 31,
    Russian: 32,
    ChineseSimplified: 33,
    Flemish: 34,
    IrishGaelic: 35,
    Albanian: 36,
    Romanian: 37,
    Czech: 38,
    Slovak: 39,
    Slovenian: 40,
    Yiddish: 41,
    Serbian: 42,
    Macedonian: 43,
    Bulgarian: 44,
    Ukrainian: 45,
    Byelorussian: 46,
    Uzbek: 47,
    Kazakh: 48,
    AzerbaijaniCyrillicScript: 49,
    AzerbaijaniArabicScript: 50,
    Armenian: 51,
    Georgian: 52,
    Moldavian: 53,
    Kirghiz: 54,
    Tajiki: 55,
    Turkmen: 56,
    MongolianMongolianScript: 57,
    MongolianCyrillicScript: 58,
    Pashto: 59,
    Kurdish: 60,
    Kashmiri: 61,
    Sindhi: 62,
    Tibetan: 63,
    Nepali: 64,
    Sanskrit: 65,
    Marathi: 66,
    Bengali: 67,
    Assamese: 68,
    Gujarati: 69,
    Punjabi: 70,
    Oriya: 71,
    Malayalam: 72,
    Kannada: 73,
    Tamil: 74,
    Telugu: 75,
    Sinhalese: 76,
    Burmese: 77,
    Khmer: 78,
    Lao: 79,
    Vietnamese: 80,
    Indonesian: 81,
    Tagalog: 82,
    MalayRomanScript: 83,
    MalayArabicScript: 84,
    Amharic: 85,
    Tigrinya: 86,
    Galla: 87,
    Somali: 88,
    Swahili: 89,
    KinyarwandaRuanda: 90,
    Rundi: 91,
    NyanjaChewa: 92,
    Malagasy: 93,
    Esperanto: 94,
    Welsh: 128,
    Basque: 129,
    Catalan: 130,
    Latin: 131,
    Quechua: 132,
    Guarani: 133,
    Aymara: 134,
    Tatar: 135,
    Uighur: 136,
    Dzongkha: 137,
    JavaneseRomanScript: 138,
    SundaneseRomanScript: 139,
    Galician: 140,
    Afrikaans: 141,
    Breton: 142,
    Inuktitut: 143,
    ScottishGaelic: 144,
    ManxGaelic: 145,
    IrishGaelicWithDotAbove: 146,
    Tongan: 147,
    GreekPolytonic: 148,
    Greenlandic: 149,
    AzerbaijaniRomanScript: 150,
}
